# Generated by Django 4.0.1 on 2022-01-20 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_compny',
            new_name='product_comapny',
        ),
    ]
