# Generated by Django 4.0.1 on 2022-01-20 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_product_compny_product_product_comapny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_comapny',
            new_name='product_company',
        ),
    ]
